### ISSUE TITLE
v6 checklist

### ISSUE THREAD

**Issue by puzrin** [nodeca/url-unshort#11]
- [ ] drop `mdurl`
- [ ] revisit returned errors
   - [ ] what is criteria of cache store
- [ ] consider support `select` in `.add()`
  - [ ] drop `src` attr check
  - [ ] document `select` rule (it's for `<a>` elements only) 
- [ ] ? consider support `text_select`
